version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: node:10.9.0

    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: System information
          command: |
            echo "node $(node -v)"
            echo "npm $(npm -v)"
      - run:
          name: Install dependencies
          command: npm install --no-package-lock
      - run:
          name: Bootstrap packages
          command: npm run bootstrap
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm test
      - save_cache:
          key: npm-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
